//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nostrfi.Relay {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RelayResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RelayResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nostrfi.Relay.RelayResources", typeof(RelayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConnectionStringConnectionException {
            get {
                return ResourceManager.GetString("ConnectionStringConnectionException", resourceCulture);
            }
        }
        
        internal static string ConnectionStringsExceptionMessage {
            get {
                return ResourceManager.GetString("ConnectionStringsExceptionMessage", resourceCulture);
            }
        }
        
        internal static string ConnectionStringInvalidDefined {
            get {
                return ResourceManager.GetString("ConnectionStringInvalidDefined", resourceCulture);
            }
        }
        
        internal static string ConnectionStringsInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringsInvalid", resourceCulture);
            }
        }
        
        internal static string DatabaseConnectionSuccess {
            get {
                return ResourceManager.GetString("DatabaseConnectionSuccess", resourceCulture);
            }
        }
        
        internal static string DatabaseConnectionFailure {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailure", resourceCulture);
            }
        }
    }
}
